export interface KnownHttpRoute {
  method: "GET" | "POST" | "DELETE";
  pathname: string;
}

export const KNOWN_HTTP_ROUTES: readonly KnownHttpRoute[] = [
  { method: "GET", pathname: "/api/health" },
  { method: "GET", pathname: "/api/auth-info" },
  { method: "POST", pathname: "/api/login" },
  { method: "GET", pathname: "/api/auth/session" },
  { method: "GET", pathname: "/api/bootstrap" },
  { method: "GET", pathname: "/api/registry/hosts" },
  { method: "POST", pathname: "/api/registry/hosts" },
  { method: "DELETE", pathname: "/api/registry/hosts/host" },
  { method: "GET", pathname: "/api/session-audit" },
  { method: "GET", pathname: "/api/doctor" },
  { method: "GET", pathname: "/api/agent-profile" },
  { method: "GET", pathname: "/api/streams" },
  { method: "GET", pathname: "/api/helpers/windows/win/bootstrap" },
  { method: "GET", pathname: "/api/helpers/windows/win" },
  { method: "GET", pathname: "/api/streams/host/request" },
  { method: "POST", pathname: "/api/streams/host/request" },
  { method: "DELETE", pathname: "/api/streams/host/request/request" },
  { method: "DELETE", pathname: "/api/session-audit/tmux/session" },
  { method: "POST", pathname: "/api/settings" },
  { method: "POST", pathname: "/api/workspaces" },
  { method: "POST", pathname: "/api/workspaces/reorder" },
  { method: "POST", pathname: "/api/notifications" },
  { method: "POST", pathname: "/api/agent-events" },
  { method: "GET", pathname: "/api/delegations/run" },
  { method: "POST", pathname: "/api/run-events" },
  { method: "POST", pathname: "/api/media" },
  { method: "POST", pathname: "/api/clipboard" },
  { method: "POST", pathname: "/api/panes/pane/paste-images" },
  { method: "DELETE", pathname: "/api/panes/pane/paste-images/stage" },
  { method: "POST", pathname: "/api/panes/pane/attachments" },
  { method: "POST", pathname: "/api/notifications/notification/read" },
  { method: "POST", pathname: "/api/workspaces/workspace/notifications/read" },
  { method: "DELETE", pathname: "/api/workspaces/workspace" },
  { method: "POST", pathname: "/api/workspaces/workspace/title" },
  { method: "POST", pathname: "/api/workspaces/workspace/auto-title" },
  { method: "POST", pathname: "/api/workspaces/workspace/tabs" },
  { method: "DELETE", pathname: "/api/workspaces/workspace/tabs/tab" },
  { method: "POST", pathname: "/api/workspaces/workspace/tabs/tab/title" },
  { method: "POST", pathname: "/api/tabs/tab/split" },
  { method: "POST", pathname: "/api/tabs/tab/split-ratio" },
  { method: "POST", pathname: "/api/panes/pane/input" },
  { method: "POST", pathname: "/api/panes/pane/reviews" },
  { method: "POST", pathname: "/api/panes/pane/notifications/read" },
  { method: "DELETE", pathname: "/api/tabs/tab/panes/pane" },
  { method: "GET", pathname: "/api/attachments/pane/file" },
];
