export interface RetroBootStep {
  text: string;
  delay: number;
  typedFrom?: number;
}

export interface RetroBootProfile {
  id: string;
  name: string;
  ariaLabel: string;
  columns: number;
  rows: number;
  fontFamily: string;
  fontSize: { desktop: number; mobile: number };
  colors: {
    page: string;
    border: string;
    background: string;
    foreground: string;
  };
  bootStatus: string;
  showBootArtwork?: boolean;
  graphicalShell?: "risc-os" | "atari-st" | "lisa" | "irix" | "nextstep" | "macintosh" | "os2";
  boot: readonly RetroBootStep[];
  auth: {
    required: string;
    unavailable: string;
    tokenRequired: readonly string[];
    usernamePrompt: string;
    passwordPrompt: string;
    verifying: string;
    failed: string;
    granted: string;
    ready: string;
  };
}

const step = (text: string, delay = 90): RetroBootStep => ({ text, delay });
const typed = (text: string, delay = 90, prompt = ""): RetroBootStep => ({
  text: `${prompt}${text}`,
  delay,
  typedFrom: prompt.length,
});

const standardAuth = {
  required: "\nAUTHENTICATION REQUIRED\n",
  unavailable: "AUTH SERVICE UNAVAILABLE\n",
  tokenRequired: ["ACCESS TOKEN REQUIRED.\n", "OPEN STARTUP URL WITH ?TOKEN=...\n"],
  usernamePrompt: "USERNAME> ",
  passwordPrompt: "PASSWORD> ",
  verifying: "VERIFYING...\n",
  failed: "LOGIN FAILED\n",
  granted: "\nACCESS GRANTED.\n",
  ready: "WMUX READY.\n",
} as const;

export const RETRO_BOOT_PROFILES: readonly RetroBootProfile[] = [
  {
    id: "commodore-64",
    name: "Commodore 64",
    ariaLabel: "Commodore 64 authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"C64 Pro Mono", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#7869c4", border: "#7869c4", background: "#40318d", foreground: "#a5a0e0" },
    bootStatus: "Reading Commodore disk directory",
    showBootArtwork: false,
    boot: [
      step("    **** COMMODORE 64 BASIC V2 ****\n\n", 120),
      step(" 64K RAM SYSTEM  38911 BASIC BYTES FREE\n\n"),
      step("READY.\n", 120),
      typed('LOAD "$",8\n\n', 90),
      step("SEARCHING FOR $\nLOADING\nREADY.\n", 110),
      typed("LIST\n\n", 70),
      step('0 "WMUX BOOT DISK" 64 2A\n'),
      step('4    "GHOSTTY"          PRG\n', 45),
      step('8    "MACHINES"         SEQ\n', 45),
      step('12   "WORKSPACES"       SEQ\n', 45),
      step('16   "SESSIONS"         PRG\n', 45),
      step("644 BLOCKS FREE.\n\nREADY.\n", 90),
      typed('LOAD "*",8\n\n', 90),
      step("SEARCHING FOR *\nLOADING\nREADY.\n", 110),
      typed("RUN\n", 80),
    ],
    auth: standardAuth,
  },
  {
    id: "commodore-128",
    name: "Commodore 128",
    ariaLabel: "Commodore 128 authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"C64 Pro Mono", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#99a1ff", border: "#99a1ff", background: "#3436a8", foreground: "#aeb5ff" },
    bootStatus: "Starting Commodore 128 CP/M services",
    showBootArtwork: false,
    boot: [
      step("COMMODORE BASIC V7.0 122365 BYTES FREE\n", 110),
      step("  (C)1986 COMMODORE ELECTRONICS, LTD.\n"),
      step("       (C)1977 MICROSOFT CORP.\n"),
      step("         ALL RIGHTS RESERVED\n\n", 120),
      step("READY.\n", 100),
      typed('DIRECTORY "WMUX"\n\n'),
      step('"GHOSTTY"       PRG   "MACHINES"  SEQ\n', 55),
      step('"WORKSPACES"    SEQ   "SESSIONS"  PRG\n', 55),
      step("READY.\n", 80),
      typed('DLOAD "WMUX"\n', 90),
      step("SEARCHING\nLOADING\nREADY.\n", 120),
      typed("RUN\n", 80),
    ],
    auth: standardAuth,
  },
  {
    id: "apple-iie",
    name: "Apple IIe",
    ariaLabel: "Apple IIe authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro Apple II", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#071109", border: "#101d12", background: "#030904", foreground: "#72db76" },
    bootStatus: "Booting Apple DOS",
    showBootArtwork: false,
    boot: [
      step("APPLE ][\n", 150),
      step("DOS VERSION 3.3  SYSTEM MASTER\n\n", 100),
      typed("CATALOG\n\n", 80, "]"),
      step("DISK VOLUME 254\n\n"),
      step(" A 002 HELLO\n", 45),
      step(" B 018 GHOSTTY\n", 45),
      step(" B 012 MACHINES\n", 45),
      step(" B 020 WORKSPACES\n", 45),
      step(" B 014 WMUX\n\n", 70),
      typed("BRUN WMUX\n", 110, "]"),
      step("WMUX SERIAL TERMINAL\n", 70),
      step("SLOT 2 ........... ONLINE\n", 60),
    ],
    auth: { ...standardAuth, failed: "?ACCESS DENIED\n]" },
  },
  {
    id: "ibm-pc-at",
    name: "386-class PC",
    ariaLabel: "386 PC BIOS and DOS authentication console",
    columns: 80,
    rows: 25,
    fontFamily: '"Retro IBM CGA", monospace',
    fontSize: { desktop: 15, mobile: 6 },
    colors: { page: "#050505", border: "#111111", background: "#000000", foreground: "#c9c9c9" },
    bootStatus: "Running 386 BIOS power-on self-test",
    showBootArtwork: false,
    boot: [
      step("American Megatrends 386DX BIOS (C)1989\n", 130),
      step("\n016384 KB OK\n", 120),
      step("Keyboard .............. Detected\n", 55),
      step("Floppy Drive A: ....... 1.44 MB\n", 55),
      step("Primary Master: ....... WMUX-IDE 40MB\n", 65),
      step("\nStarting MS-DOS...\n", 120),
      step("HIMEM is testing extended memory...done.\n", 70),
      step("GHOSTTY.SYS installed\n", 55),
      step("WMUX network redirector loaded\n\n", 65),
      typed("WMUX\n", 90, "C:\\>"),
    ],
    auth: { ...standardAuth, failed: "Access denied\nC:\\>" },
  },
  {
    id: "bbc-micro",
    name: "BBC Micro",
    ariaLabel: "BBC Micro authentication console",
    columns: 40,
    rows: 32,
    fontFamily: '"Retro BBC Micro", monospace',
    fontSize: { desktop: 16, mobile: 10 },
    colors: { page: "#050505", border: "#151515", background: "#050505", foreground: "#f1f1f1" },
    bootStatus: "Reading BBC Micro filing system",
    showBootArtwork: false,
    boot: [
      step("BBC Computer 32K\n\n", 130),
      step("Acorn DFS\n\nBASIC\n\n>"),
      typed("*CAT\n\n", 80),
      step("Drive 0             Option 0\n", 100),
      step("Dir. :0.$           Lib. :0.$\n\n"),
      step("    GHOSTTY      MACHINES\n", 50),
      step("    SESSIONS     WORKSPACE\n", 50),
      step("    WMUX\n\n>"),
      typed('CHAIN "WMUX"\n', 100),
      step("WMUX NETWORK FILING SYSTEM\n", 80),
      step("HOST ADAPTER .......... OK\n", 60),
      step("TERMINAL DRIVER ....... OK\n", 60),
    ],
    auth: { ...standardAuth, failed: "BAD USER\n>" },
  },
  {
    id: "acorn-archimedes",
    name: "Acorn Archimedes",
    ariaLabel: "Acorn Archimedes RISC OS authentication console",
    columns: 80,
    rows: 32,
    fontFamily: '"Retro BBC Micro", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#d4d4d4", border: "#d4d4d4", background: "#eeeeee", foreground: "#111111" },
    bootStatus: "Starting Acorn RISC OS",
    showBootArtwork: false,
    graphicalShell: "risc-os",
    boot: [
      step("Acorn Archimedes A3000\n", 140),
      step("RISC OS 3.11  (C) Acorn Computers Ltd\n\n", 100),
      step("2048K memory\n", 70),
      step("FileCore ................. ready\n", 50),
      step("ADFS ..................... ready\n", 50),
      step("Internet ................. ready\n", 50),
      step("GhosttyFS ................. ready\n\n", 60),
      step("*CAT\n", 70),
      step("!Boot  !Ghostty  !Machines  !WMux\n", 60),
      step("*WMUX\n", 90),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER NAME> ", failed: "NOT AUTHORISED\n*" },
  },
  {
    id: "trs-80-model-4",
    name: "TRS-80 Model 4",
    ariaLabel: "TRS-80 Model 4 authentication console",
    columns: 64,
    rows: 24,
    fontFamily: '"Retro IBM 2915", monospace',
    fontSize: { desktop: 16, mobile: 8 },
    colors: { page: "#0b120c", border: "#111d12", background: "#020703", foreground: "#82c98a" },
    bootStatus: "Booting TRSDOS",
    showBootArtwork: false,
    boot: [
      step("TRS-80 MODEL 4\n", 140),
      step("RADIO SHACK TRSDOS 6.2\n\n", 100),
      step("DATE? 07/10/86\nTIME? 12:00:00\n\n", 80),
      step("TRSDOS READY\n", 80),
      typed("DIR :0\n", 70),
      step("GHOSTTY/CMD   MACHINES/DAT   SESSION/DAT\n", 55),
      step("WMUX/CMD      WORKSPAC/DAT\n", 55),
      typed("WMUX\n", 90),
      step("WMUX RS-232 HOST LINK\n", 70),
    ],
    auth: { ...standardAuth, failed: "PASSWORD ERROR\nTRSDOS READY\n" },
  },
  {
    id: "zx-spectrum",
    name: "ZX Spectrum",
    ariaLabel: "ZX Spectrum authentication console",
    columns: 32,
    rows: 24,
    fontFamily: '"Retro Spectrum", monospace',
    fontSize: { desktop: 18, mobile: 11 },
    colors: { page: "#d7d7d7", border: "#d7d7d7", background: "#f3f3f3", foreground: "#111111" },
    bootStatus: "Loading ZX Spectrum tape",
    showBootArtwork: false,
    boot: [
      step("\n (C) 1982 Sinclair Research Ltd\n\n", 150),
      typed('LOAD ""\n', 110),
      step("Program: WMUX\n", 90),
      step("Bytes: GHOSTTY\n", 55),
      step("Bytes: MACHINES\n", 55),
      step("Bytes: SESSIONS\n", 55),
      step("Bytes: WORKSPACE\n", 55),
      step("\n0 OK, 0:1\n", 100),
      typed("RUN\n", 80),
      step("WMUX TERMINAL LINK\n", 70),
    ],
    auth: { ...standardAuth, failed: "R Tape loading error, 0:1\n" },
  },
  {
    id: "atari-st",
    name: "Atari ST",
    ariaLabel: "Atari ST authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"Retro Atari ST", monospace',
    fontSize: { desktop: 16, mobile: 10 },
    colors: { page: "#cfd5d5", border: "#cfd5d5", background: "#f3f5f5", foreground: "#111111" },
    bootStatus: "Starting Atari TOS",
    showBootArtwork: false,
    graphicalShell: "atari-st",
    boot: [
      step("ATARI 1040ST\n", 130),
      step("TOS 1.04  (C)1989 ATARI CORP.\n\n"),
      step("MEMORY TEST ............. 1024K\n", 80),
      step("FLOPPY A: ............... READY\n", 65),
      step("ACSI HOST ADAPTER ....... READY\n", 65),
      step("\nAUTO\\WMUX.PRG\n", 110),
      step("GEMDOS TERMINAL SERVICES\n", 70),
      step("GHOSTTY.PRG ............. LOADED\n", 55),
      step("WMUX.RSC ................ LOADED\n", 55),
    ],
    auth: { ...standardAuth, failed: "ACCESS DENIED\n" },
  },
  {
    id: "amiga-workbench",
    name: "Amiga Workbench",
    ariaLabel: "Amiga Workbench Shell authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"Retro Amiga Topaz", monospace',
    fontSize: { desktop: 16, mobile: 9 },
    colors: { page: "#ffffff", border: "#ffffff", background: "#aaaaaa", foreground: "#111111" },
    bootStatus: "Opening AmigaShell",
    boot: [
      step("AmigaShell\n", 130),
      step("Copyright 1987 Commodore-Amiga, Inc.\n\n", 90),
      typed("assign WMUX: NET:wmux\n", 75, "1.System:> "),
      typed("WMUX:wmux\n", 100, "1.System:> "),
      step("wmux-handler ............. loaded\n", 55),
      step("workspace.library ........ loaded\n", 55),
    ],
    auth: {
      ...standardAuth,
      required: "\nAuthentication required.\n",
      usernamePrompt: "User name: ",
      passwordPrompt: "Password: ",
      verifying: "Checking...\n",
      failed: "Login incorrect\n1.System:> ",
      granted: "\nAccess granted.\n",
      ready: "WMUX ready.\n",
    },
  },
  {
    id: "osborne-1",
    name: "Osborne 1",
    ariaLabel: "Osborne 1 CP/M authentication console",
    columns: 52,
    rows: 24,
    fontFamily: '"Retro VT100", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#101711", border: "#1a241b", background: "#071008", foreground: "#86d68c" },
    bootStatus: "Booting Osborne CP/M",
    showBootArtwork: false,
    boot: [
      step("OSBORNE 1\n", 150),
      step("64K CP/M VERSION 2.2\n", 90),
      step("COPYRIGHT 1979 (C) BY DIGITAL RESEARCH\n\n"),
      typed("DIR\n", 80, "A>"),
      step("A: WMUX     COM : GHOSTTY  COM : LOGIN    COM\n", 55),
      step("A: MACHINE  DAT : SESSION  DAT : WORKSPAC DAT\n", 55),
      typed("WMUX\n", 100, "A>"),
      step("WMUX REMOTE TERMINAL 1.0\n", 70),
      step("SERIAL PORT .............. CONNECTED\n", 60),
    ],
    auth: { ...standardAuth, failed: "NO ACCESS\nA>" },
  },
  {
    id: "sinclair-ql",
    name: "Sinclair QL",
    ariaLabel: "Sinclair QL authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"Retro Spectrum", monospace',
    fontSize: { desktop: 17, mobile: 10 },
    colors: { page: "#d4d4d4", border: "#d4d4d4", background: "#090909", foreground: "#eeeeee" },
    bootStatus: "Starting Sinclair QDOS",
    showBootArtwork: false,
    boot: [
      step("Sinclair QL\n", 140),
      step("QDOS 1.03\n\n", 90),
      step("F1... MONITOR\nF2... TV\n\n", 100),
      typed("F1\n", 80),
      step("QL SuperBASIC\n", 80),
      typed('LOAD mdv1_WMUX_bas\n', 110),
      step("NETWORK DRIVER LOADED\n", 60),
      step("GHOSTTY CHANNEL OPEN\n", 60),
      typed("RUN\n", 70),
    ],
    auth: { ...standardAuth, failed: "NOT FOUND\n" },
  },
  {
    id: "amstrad-cpc",
    name: "Amstrad CPC 464",
    ariaLabel: "Amstrad CPC authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"Retro Amstrad CPC", monospace',
    fontSize: { desktop: 16, mobile: 10 },
    colors: { page: "#071c68", border: "#071c68", background: "#071c68", foreground: "#ffe746" },
    bootStatus: "Loading Amstrad cassette",
    showBootArtwork: false,
    boot: [
      step("Amstrad 64K Microcomputer\n", 130),
      step("(v1)\n\n", 80),
      step("BASIC 1.0\n\nReady\n", 100),
      typed('RUN"WMUX\n', 100),
      step("Press PLAY then any key:\n", 100),
      step("Loading WMUX block 1\n", 70),
      step("Loading WMUX block 2\n", 70),
      step("WMUX HOST TERMINAL\n", 80),
    ],
    auth: { ...standardAuth, failed: "Login error\nReady\n" },
  },
  {
    id: "msx2",
    name: "MSX2",
    ariaLabel: "MSX2 BASIC authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro MSX", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#2466aa", border: "#2466aa", background: "#2466aa", foreground: "#ffffff" },
    bootStatus: "Starting MSX BASIC",
    boot: [
      step("MSX BASIC version 2.1\n", 130),
      step("Copyright 1985 by Microsoft\n", 80),
      step("28815 Bytes free\n\nOk\n", 100),
      typed("FILES\n", 70),
      step('GHOSTTY BAS   MACHINE DAT   WMUX    BAS\n', 55),
      step('SESSION DAT   WORKSPAC DAT\n', 55),
      step("Ok\n", 70),
      typed("CALL WMUX\n", 90),
      step("WMUX HOST INTERFACE\n", 70),
    ],
    auth: { ...standardAuth, failed: "Illegal function call\nOk\n" },
  },
  {
    id: "apple-lisa",
    name: "Apple Lisa",
    ariaLabel: "Apple Lisa service terminal authentication console",
    columns: 60,
    rows: 24,
    fontFamily: '"Retro Lisa Console", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#d8d1bf", border: "#d8d1bf", background: "#f2ecdc", foreground: "#161616" },
    bootStatus: "Running Apple Lisa self-test",
    showBootArtwork: false,
    graphicalShell: "lisa",
    boot: [
      step("LISA 2/10 ROM SELF TEST\n", 140),
      step("MEMORY .................... PASSED\n", 55),
      step("I/O BOARD ................. PASSED\n", 55),
      step("PROFILE DRIVE ............. ONLINE\n", 65),
      step("\nLISA TERMINAL 3.1\n", 100),
      step("Loading office system services...\n", 70),
      step("ghostty.device ............. loaded\n", 55),
      step("wmux.session ............... loaded\n", 55),
    ],
    auth: { ...standardAuth, usernamePrompt: "User name: ", passwordPrompt: "Password: ", failed: "Login incorrect\n" },
  },
  {
    id: "vax-vms",
    name: "VAX/VMS",
    ariaLabel: "VAX VMS VT100 authentication console",
    columns: 80,
    rows: 24,
    fontFamily: '"Retro VT100", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#101711", border: "#1a241b", background: "#020803", foreground: "#72d47b" },
    bootStatus: "Starting VAX/VMS",
    showBootArtwork: false,
    boot: [
      step("%SYSBOOT-I-SYSBOOT Mapping the SYSDUMP.DMP on the System Disk\n", 110),
      step("%SYSBOOT-I-SYSBOOT VAX/VMS Version V5.5-2\n", 80),
      step("%MOUNT-I-MOUNTED, SYS$SYSDEVICE mounted\n", 55),
      step("%SET-I-INTSET, login interactive limit = 64\n", 55),
      step("%STARTUP-I-STARTUP, VMS startup begun\n", 70),
      step("%WMUX-I-ONLINE, terminal services available\n\n", 75),
      step("WMUX VAX/VMS REMOTE ACCESS\n", 90),
    ],
    auth: {
      ...standardAuth,
      usernamePrompt: "Username: ",
      passwordPrompt: "Password: ",
      failed: "%LOGIN-F-USERAUTH, authorization failure\n",
      granted: "\nWelcome to VAX/VMS\n",
    },
  },
  {
    id: "sun-sparcstation",
    name: "Sun SPARCstation",
    ariaLabel: "Sun SPARCstation SunOS authentication console",
    columns: 80,
    rows: 34,
    fontFamily: '"Retro VT100", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#ece9dd", border: "#ece9dd", background: "#f4f1e7", foreground: "#151515" },
    bootStatus: "Booting SunOS",
    showBootArtwork: false,
    boot: [
      step("SPARCstation 2, No Keyboard\n", 130),
      step("ROM Rev. 2.9, 64 MB memory installed\n", 70),
      step("Ethernet address 8:0:20:7a:11:42\n\n", 70),
      step("Testing network\n", 55),
      step("Testing SBus slots\n", 55),
      typed("boot\n", 90, "ok "),
      step("Boot device: sd  File and args:\n", 70),
      step("SunOS Release 4.1.4 (WMUX) #1\n", 75),
      step("checking filesystems... done\n", 55),
      step("starting network daemons: inetd routed\n", 55),
      step("wmux-sun console login\n", 80),
    ],
    auth: {
      ...standardAuth,
      required: "\n",
      usernamePrompt: "login: ",
      passwordPrompt: "Password: ",
      verifying: "\n",
      failed: "Login incorrect\n",
      granted: "\nLast login: Fri Jul 10 12:00:00\n",
    },
  },
  {
    id: "sgi-irix",
    name: "SGI Indigo IRIX",
    ariaLabel: "SGI Indigo IRIX authentication console",
    columns: 80,
    rows: 30,
    fontFamily: '"Retro IBM 2915", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#5c55a5", border: "#5c55a5", background: "#201d38", foreground: "#f3eee2" },
    bootStatus: "Starting SGI IRIX",
    graphicalShell: "irix",
    boot: [
      step("Running power-on diagnostics...\n", 130),
      step("System: IP22\n", 55),
      step("Processor: 150 MHz R4400, 1 MB cache\n", 55),
      step("Memory size: 64 Mbytes\n", 55),
      step("Graphics: GR2-Elan\n", 55),
      step("\nStarting up the system...\n", 100),
      step("IRIX Release 6.5 IP22 Version 05190004\n", 70),
      step("Mounting local filesystems: / /usr /var\n", 55),
      step("Starting network: routed inetd nsd\n", 55),
      step("wmux console\n", 80),
    ],
    auth: {
      ...standardAuth,
      required: "\n",
      usernamePrompt: "login: ",
      passwordPrompt: "Password: ",
      verifying: "\n",
      failed: "Login incorrect\n",
      granted: "\nIRIX Release 6.5\n",
    },
  },
  {
    id: "nextcube",
    name: "NeXTcube",
    ariaLabel: "NeXTcube NeXTSTEP authentication console",
    columns: 80,
    rows: 30,
    fontFamily: '"Retro Lisa Console", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#bcbcbc", border: "#bcbcbc", background: "#dedede", foreground: "#111111" },
    bootStatus: "Booting NeXTSTEP",
    graphicalShell: "nextstep",
    boot: [
      step("NeXT Computer, Inc.\n", 140),
      step("NeXT ROM Monitor 2.5 (v66)\n", 70),
      step("Testing memory: 32 MB\n", 65),
      step("Booting from SCSI disk @ 0\n\n", 80),
      step("NeXT Mach Operating System\n", 85),
      step("Loading /mach_kernel\n", 55),
      step("root on sd0a\n", 55),
      step("starting system services\n", 55),
      step("starting network services\n", 55),
      step("NeXTSTEP Release 3.3\n", 80),
      step("wmux console\n", 70),
    ],
    auth: {
      ...standardAuth,
      required: "\n",
      usernamePrompt: "login: ",
      passwordPrompt: "Password: ",
      verifying: "\n",
      failed: "Login incorrect\n",
      granted: "\nWelcome to NeXTSTEP\n",
    },
  },
  {
    id: "pdp-11-rt11",
    name: "PDP-11 RT-11",
    ariaLabel: "PDP-11 RT-11 authentication console",
    columns: 80,
    rows: 24,
    fontFamily: '"Retro VT100", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#0e1710", border: "#17251a", background: "#020803", foreground: "#69cc75" },
    bootStatus: "Booting PDP-11 RT-11",
    showBootArtwork: false,
    boot: [
      step("BOOT V4.0\n", 140),
      step("\nRT-11SJ  V05.03\n\n", 100),
      typed("DATE 10-JUL-86\n", 65, "."),
      typed("TIME 12:00:00\n", 65, "."),
      typed("DIR SY:\n", 70, "."),
      step("GHOSTY.SAV    MACHINE.DAT    SESSION.DAT\n", 55),
      step("WMUX.SAV      WORKSPC.DAT\n", 55),
      typed("R WMUX\n", 90, "."),
      step("WMUX DL11 TERMINAL LINK\n", 75),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", failed: "?LOGIN-F-INVALID USER\n." },
  },
  {
    id: "ibm-3270-mvs",
    name: "IBM 3270 MVS",
    ariaLabel: "IBM 3270 MVS authentication terminal",
    columns: 80,
    rows: 24,
    fontFamily: '"Retro IBM 2915", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#111711", border: "#1b251c", background: "#020703", foreground: "#66d37a" },
    bootStatus: "Connecting IBM 3270 terminal",
    showBootArtwork: false,
    boot: [
      step("IBM 3278 DISPLAY STATION\n", 130),
      step("CONTROL UNIT ADDRESS 02A0\n", 65),
      step("TERMINAL TEST ............... READY\n", 65),
      step("\nISTINCLM LOGON REQUEST RECEIVED\n", 90),
      step("IST663I INIT OTHER REQUEST\n", 55),
      step("IKJ56455I WMUX/MVS TIME SHARING READY\n\n", 80),
      step("WELCOME TO WMUX/MVS\n", 80),
    ],
    auth: {
      ...standardAuth,
      required: "\n",
      usernamePrompt: "USERID ===> ",
      passwordPrompt: "PASSWORD ==> ",
      verifying: "\n",
      failed: "IKJ56420I USERID OR PASSWORD NOT AUTHORIZED\n",
      granted: "\nIKJ56470I LOGON IN PROGRESS\n",
    },
  },
  {
    id: "macintosh-system-6",
    name: "Macintosh System 6",
    ariaLabel: "Macintosh System 6 terminal authentication console",
    columns: 80,
    rows: 24,
    fontFamily: '"Retro Lisa Console", monospace',
    fontSize: { desktop: 15, mobile: 7 },
    colors: { page: "#b9b9b9", border: "#dedede", background: "#ffffff", foreground: "#111111" },
    bootStatus: "Starting Macintosh System 6",
    graphicalShell: "macintosh",
    boot: [
      step("Welcome to Macintosh.\n", 150),
      step("System 6.0.8\n\n", 90),
      step("Finder ................ ready\n", 55),
      step("MacTCP ................ ready\n", 55),
      step("Opening WMUX Terminal...\n", 90),
    ],
    auth: {
      ...standardAuth,
      required: "\nRemote Access\n",
      usernamePrompt: "User name: ",
      passwordPrompt: "Password: ",
      verifying: "Connecting...\n",
      failed: "The name or password is incorrect.\n",
      granted: "\nConnection accepted.\n",
    },
  },
  {
    id: "ti-99-4a",
    name: "TI-99/4A",
    ariaLabel: "TI-99/4A terminal authentication console",
    columns: 32,
    rows: 24,
    fontFamily: '"Retro Tatung Einstein", monospace',
    fontSize: { desktop: 18, mobile: 10 },
    colors: { page: "#62c9d1", border: "#62c9d1", background: "#54bfc8", foreground: "#162f7a" },
    bootStatus: "Starting TI BASIC",
    showBootArtwork: false,
    boot: [
      step("TEXAS INSTRUMENTS\n", 140),
      step("HOME COMPUTER\n\n", 90),
      step("1 FOR TI BASIC\n", 70),
      step("2 FOR WMUX TERMINAL\n\n", 70),
      typed("2\n", 90),
      step("WMUX RS232 TERMINAL\n", 80),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", passwordPrompt: "PASS> ", failed: "BAD VALUE\n" },
  },
  {
    id: "trs-80-coco",
    name: "TRS-80 Color Computer",
    ariaLabel: "Color Computer BASIC authentication console",
    columns: 32,
    rows: 16,
    fontFamily: '"Retro Tatung Einstein", monospace',
    fontSize: { desktop: 18, mobile: 10 },
    colors: { page: "#0b1510", border: "#14231a", background: "#0b120d", foreground: "#76d789" },
    bootStatus: "Starting Extended Color BASIC",
    showBootArtwork: false,
    boot: [
      step("EXTENDED COLOR BASIC 1.1\n", 140),
      step("COPYRIGHT 1982 TANDY\n\n", 90),
      step("OK\n", 80),
      typed('RUN "WMUX"\n', 100),
      step("WMUX SERIAL LINK\n", 75),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER? ", passwordPrompt: "PASS? ", failed: "?SN ERROR\nOK\n" },
  },
  {
    id: "amstrad-pcw",
    name: "Amstrad PCW 8256",
    ariaLabel: "Amstrad PCW CP/M Plus authentication console",
    columns: 90,
    rows: 32,
    fontFamily: '"Retro Amstrad CPC", monospace',
    fontSize: { desktop: 14, mobile: 6 },
    colors: { page: "#0b130d", border: "#15251a", background: "#040a05", foreground: "#72c87c" },
    bootStatus: "Booting CP/M Plus",
    showBootArtwork: false,
    boot: [
      step("Please insert a system disc, then press SPACE\n", 150),
      step("\nLoading CP/M Plus...\n", 120),
      step("CP/M Plus Amstrad Consumer Electronics plc\n\n", 85),
      typed("WMUX\n", 90, "A>"),
      step("WMUX communications terminal\n", 70),
    ],
    auth: { ...standardAuth, usernamePrompt: "User: ", passwordPrompt: "Password: ", failed: "Login failed\nA>" },
  },
  {
    id: "sharp-x68000",
    name: "Sharp X68000",
    ariaLabel: "Sharp X68000 Human68k authentication console",
    columns: 96,
    rows: 32,
    fontFamily: '"Retro IBM CGA", monospace',
    fontSize: { desktop: 13, mobile: 6 },
    colors: { page: "#111111", border: "#1c1c1c", background: "#050505", foreground: "#e7e7e7" },
    bootStatus: "Booting Human68k",
    showBootArtwork: false,
    boot: [
      step("Human68k version 3.02\n", 140),
      step("Copyright 1987-1993 SHARP/Hudson\n\n", 90),
      typed("path A:\\BIN\n", 60, "A:\\>"),
      typed("wmux.x\n", 90, "A:\\>"),
      step("WMUX RS-232C terminal\n", 70),
    ],
    auth: { ...standardAuth, usernamePrompt: "login: ", passwordPrompt: "password: ", failed: "Login incorrect\n" },
  },
  {
    id: "nec-pc-9801",
    name: "NEC PC-9801",
    ariaLabel: "NEC PC-9801 MS-DOS authentication console",
    columns: 80,
    rows: 25,
    fontFamily: '"Retro IBM CGA", monospace',
    fontSize: { desktop: 15, mobile: 6 },
    colors: { page: "#050505", border: "#111111", background: "#000000", foreground: "#d7d7d7" },
    bootStatus: "Booting PC-98 MS-DOS",
    showBootArtwork: false,
    boot: [
      step("NEC PC-9801 SERIES\n", 130),
      step("MEMORY 640KB OK\n", 90),
      step("Starting MS-DOS Version 5.0A...\n\n", 110),
      typed("WMUX.EXE\n", 90, "A:\\>"),
      step("WMUX PC-9801 terminal driver\n", 70),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", passwordPrompt: "PASSWORD> ", failed: "ACCESS DENIED\nA:\\>" },
  },
  {
    id: "os2-warp",
    name: "IBM OS/2 Warp",
    ariaLabel: "OS/2 Warp command prompt authentication console",
    columns: 80,
    rows: 25,
    fontFamily: '"Retro IBM CGA", monospace',
    fontSize: { desktop: 15, mobile: 6 },
    colors: { page: "#111827", border: "#1b2d52", background: "#000000", foreground: "#d7d7d7" },
    bootStatus: "Starting OS/2 Warp",
    showBootArtwork: false,
    graphicalShell: "os2",
    boot: [
      step("OS/2 Warp Version 3\n", 140),
      step("The Operating System/2\n\n", 90),
      step("Loading BASEDEV drivers...\n", 65),
      step("Starting Workplace Shell...\n", 80),
      step("[C:\\] WMUX.EXE\n", 90),
    ],
    auth: { ...standardAuth, usernamePrompt: "User ID: ", passwordPrompt: "Password: ", failed: "SYS0005: Access is denied.\n" },
  },
  {
    id: "enterprise-128",
    name: "Enterprise 128",
    ariaLabel: "Enterprise 128 IS-BASIC authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro Spectrum", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#101b43", border: "#1f3071", background: "#173c9b", foreground: "#f3efcf" },
    bootStatus: "Starting EXOS",
    showBootArtwork: false,
    boot: [
      step("ENTERPRISE 128\n", 140),
      step("EXOS 2.1\n\n", 90),
      typed(":BASIC\n", 80),
      step("IS-BASIC 2.1\n", 75),
      typed('RUN "WMUX"\n', 90),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER: ", passwordPrompt: "PASS: ", failed: "*** INVALID USER\n" },
  },
  {
    id: "oric-atmos",
    name: "Oric Atmos",
    ariaLabel: "Oric Atmos BASIC authentication console",
    columns: 40,
    rows: 28,
    fontFamily: '"Retro Oric Atmos", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#050505", border: "#111111", background: "#000000", foreground: "#f3f3f3" },
    bootStatus: "Starting Oric BASIC",
    showBootArtwork: false,
    boot: [
      step("ORIC EXTENDED BASIC V1.1\n", 140),
      step("(C) 1983 TANGERINE\n\n", 90),
      step("Ready\n", 80),
      typed('CLOAD"WMUX"\n', 100),
      step("Searching...\n", 75),
      step("Ready\n", 80),
      typed("RUN\n", 80),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER? ", passwordPrompt: "PASS? ", failed: "?SYNTAX ERROR\nReady\n" },
  },
  {
    id: "commodore-pet",
    name: "Commodore PET 2001",
    ariaLabel: "Commodore PET BASIC authentication console",
    columns: 40,
    rows: 25,
    fontFamily: '"Retro VIC-20", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#08110a", border: "#101d12", background: "#020603", foreground: "#75d47e" },
    bootStatus: "Starting Commodore BASIC",
    showBootArtwork: false,
    boot: [
      step("*** COMMODORE BASIC ***\n\n", 140),
      step(" 7167 BYTES FREE\n\n", 90),
      step("READY.\n", 80),
      typed('LOAD"WMUX",8\n', 100),
      step("SEARCHING FOR WMUX\nLOADING\n", 90),
      step("READY.\n", 80),
      typed("RUN\n", 80),
    ],
    auth: standardAuth,
  },
  {
    id: "commodore-vic-20",
    name: "Commodore VIC-20",
    ariaLabel: "Commodore VIC-20 BASIC authentication console",
    columns: 22,
    rows: 23,
    fontFamily: '"Retro VIC-20", monospace',
    fontSize: { desktop: 19, mobile: 12 },
    colors: { page: "#52cbd0", border: "#52cbd0", background: "#ffffff", foreground: "#214ea0" },
    bootStatus: "Starting VIC BASIC",
    showBootArtwork: false,
    boot: [
      step("**** CBM BASIC V2 ****\n", 140),
      step("3583 BYTES FREE\n\n", 90),
      step("READY.\n", 80),
      typed('LOAD"WMUX",8\n', 90),
      step("SEARCHING\nLOADING\n", 80),
      step("READY.\n", 80),
      typed("RUN\n", 80),
    ],
    auth: { ...standardAuth, tokenRequired: ["TOKEN REQUIRED.\n", "USE ?TOKEN=...\n"] },
  },
  {
    id: "sam-coupe",
    name: "SAM Coupé",
    ariaLabel: "SAM Coupé BASIC authentication console",
    columns: 32,
    rows: 24,
    fontFamily: '"Retro SAM Coupe", monospace',
    fontSize: { desktop: 18, mobile: 10 },
    colors: { page: "#d9d9d9", border: "#d9d9d9", background: "#f4f4f4", foreground: "#111111" },
    bootStatus: "Starting SAM BASIC",
    showBootArtwork: false,
    boot: [
      step("SAM COUPE 256K\n", 140),
      step("MASTER BASIC 2.1\n\n", 90),
      typed("BOOT 1\n", 80, "> "),
      step("Loading WMUX...\n", 100),
      step("WMUX serial terminal\n", 70),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", passwordPrompt: "PASS> ", failed: "Invalid argument\n" },
  },
  {
    id: "memotech-mtx",
    name: "Memotech MTX512",
    ariaLabel: "Memotech MTX BASIC authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro Memotech MTX", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#151515", border: "#202020", background: "#050505", foreground: "#eeeeee" },
    bootStatus: "Starting MTX BASIC",
    showBootArtwork: false,
    boot: [
      step("MEMOTECH MTX BASIC\n", 140),
      step("READY\n", 90),
      typed('RUN "WMUX"\n', 90, "USER "),
      step("WMUX RS232 CHANNEL OPEN\n", 75),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", passwordPrompt: "PASS> ", failed: "ERROR\nREADY\n" },
  },
  {
    id: "tatung-einstein",
    name: "Tatung Einstein",
    ariaLabel: "Tatung Einstein MOS authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro Tatung Einstein", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#0c1d44", border: "#142b62", background: "#09205c", foreground: "#f1f1d4" },
    bootStatus: "Booting MOS",
    showBootArtwork: false,
    boot: [
      step("TATUNG EINSTEIN TC-01\n", 140),
      step("MOS SYSTEM DISC\n\n", 90),
      typed("DIR\n", 75, "A>"),
      step("WMUX     COM    TERMINAL COM\n", 65),
      typed("WMUX\n", 90, "A>"),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER> ", passwordPrompt: "PASS> ", failed: "NO ACCESS\nA>" },
  },
  {
    id: "atari-8-bit",
    name: "Atari 800XL",
    ariaLabel: "Atari BASIC authentication console",
    columns: 40,
    rows: 24,
    fontFamily: '"Retro Atari 8-bit", monospace',
    fontSize: { desktop: 17, mobile: 9 },
    colors: { page: "#2444a8", border: "#2444a8", background: "#3157c7", foreground: "#b9d7ff" },
    bootStatus: "Starting Atari BASIC",
    showBootArtwork: false,
    boot: [
      step("READY\n", 140),
      typed('RUN "D:WMUX.BAS"\n', 100),
      step("LOADING WMUX TERMINAL\n", 80),
      step("R: HANDLER INSTALLED\n", 70),
    ],
    auth: { ...standardAuth, usernamePrompt: "USER? ", passwordPrompt: "PASS? ", failed: "ERROR- 165\nREADY\n" },
  },
  {
    id: "pico-8",
    name: "PICO-8",
    ariaLabel: "PICO-8 fantasy console authentication terminal",
    columns: 32,
    rows: 24,
    fontFamily: '"Retro Spectrum", monospace',
    fontSize: { desktop: 18, mobile: 11 },
    colors: { page: "#1d2b53", border: "#1d2b53", background: "#1d2b53", foreground: "#fff1e8" },
    bootStatus: "Loading PICO-8 cartridge",
    boot: [
      step("\n      PICO-8\n", 140),
      step("   FANTASY CONSOLE\n\n", 100),
      step("VERSION 0.2.6B\n", 65),
      step("(C) 2014-2024 LEXALOFFLE\n\n", 80),
      step("TYPE HELP FOR HELP\n\n", 70),
      typed("LOAD #WMUX\n", 90, "> "),
      step("LOADING CARTRIDGE...\n", 80),
      typed("RUN\n", 75, "> "),
      step("WMUX TERMINAL CART\n", 80),
    ],
    auth: {
      ...standardAuth,
      required: "\nLOGIN REQUIRED\n",
      usernamePrompt: "USER> ",
      passwordPrompt: "PASS> ",
      verifying: "CHECKING...\n",
      failed: "NOPE!\n> ",
      granted: "\nOK!\n",
    },
  },
] as const;

export const selectRetroBootProfile = (
  randomValue = Math.random(),
  previousId?: string | null,
): RetroBootProfile => {
  const candidates = RETRO_BOOT_PROFILES.filter((profile) => profile.id !== previousId);
  const pool = candidates.length > 0 ? candidates : RETRO_BOOT_PROFILES;
  const normalized = Number.isFinite(randomValue) ? Math.max(0, Math.min(randomValue, 0.999999999)) : 0;
  return pool[Math.floor(normalized * pool.length)] ?? RETRO_BOOT_PROFILES[0];
};
