#!/usr/bin/env node
import readline from "node:readline";
import { getSession, nameSession, synchronize } from "./wmux-session.mjs";
const versions = new Set(["2024-11-05", "2025-03-26", "2025-06-18", "2025-11-25"]);
const sessionId = { type: "string", description: "Exact sessionId supplied by the trusted wmux prompt hook." }, bindingId = { type: "string", description: "Exact public bindingId supplied by the same trusted wmux prompt hook." }, identity = { sessionId, bindingId };
const tools = [
  { name: "get_current_wmux_session", description: "Resolve only this explicit trusted binding; it cannot list sessions.", inputSchema: { type: "object", properties: identity, required: ["sessionId", "bindingId"], additionalProperties: false } },
  { name: "name_current_wmux_session", description: "Save an agent-chosen wmux semantic title and apply it through this binding without overriding manual wmux titles. Never reads or changes native Codex names.", inputSchema: { type: "object", properties: { ...identity, title: { type: "string", description: "Semantic task title, at most 80 characters." }, mode: { type: "string", enum: ["auto"] } }, required: ["sessionId", "bindingId", "title"], additionalProperties: false } },
  { name: "sync_current_wmux_session", description: "Reapply this session's stored wmux semantic title through the current binding, preserving manual wmux titles. Native Codex names remain independent.", inputSchema: { type: "object", properties: identity, required: ["sessionId", "bindingId"], additionalProperties: false } },
];
function result(id, value) { process.stdout.write(`${JSON.stringify({ jsonrpc: "2.0", id, result: value })}\n`); }
function error(id, code, message) { process.stdout.write(`${JSON.stringify({ jsonrpc: "2.0", id, error: { code, message }})}\n`); }
function toolResult(value, isError = false) { return { content: [{ type: "text", text: JSON.stringify(value) }], structuredContent: value, ...(isError ? { isError: true } : {}) }; }
async function call(name, args) { if (name === "get_current_wmux_session") return getSession(args?.sessionId, args?.bindingId); if (name === "name_current_wmux_session") return nameSession(args?.sessionId, args?.bindingId, args?.title, args?.mode ?? "auto"); if (name === "sync_current_wmux_session") return synchronize(args?.sessionId, args?.bindingId); throw new Error("Unknown wmux tool."); }
const input = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
input.on("line", async line => { let message; try { message = JSON.parse(line); } catch { return; } if (!message || !Object.hasOwn(message, "id")) return; try { if (message.method === "initialize") { const version = message.params?.protocolVersion; if (typeof version !== "string") return error(message.id, -32602, "MCP protocol version is required."); result(message.id, { protocolVersion: versions.has(version) ? version : "2025-11-25", capabilities: { tools: {} }, serverInfo: { name: "wmux", version: "0.4.0" } }); } else if (message.method === "ping") result(message.id, {}); else if (message.method === "tools/list") result(message.id, { tools }); else if (message.method === "tools/call") { const value = await call(message.params?.name, message.params?.arguments); result(message.id, toolResult(value, !!value.error)); } else error(message.id, -32601, "Method not found."); } catch (cause) { result(message.id, toolResult({ error: cause instanceof Error ? cause.message : "wmux tool failed." }, true)); } });
