#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
let installer = fs.readFileSync(path.join(root, "src/integrations/hooks-installer.mjs"), "utf8");
for (const name of ["opencode", "prime-agent"]) {
  // Both runtimes load TypeScript natively. Preserve the checked source in the
  // self-contained installer, without a second compilation semantics boundary.
  const source = fs.readFileSync(path.join(root, "src/integrations", `${name}.ts`), "utf8");
  const marker = `__WMUX_${name.toUpperCase().replaceAll("-", "_")}_SOURCE__`;
  if (!installer.includes(marker)) throw new Error(`Missing integration marker ${marker}`);
  installer = installer.replace(marker, () => JSON.stringify(source));
}
installer = installer.replace("#!/usr/bin/env node\n", "#!/usr/bin/env node\n// Generated by scripts/generate-hooks.mjs. Do not edit.\n");
const output = path.join(root, "scripts/wmux-hooks");
if (process.argv.includes("--check")) {
  if (fs.readFileSync(output, "utf8") !== installer) {
    throw new Error("Integration bundle is stale. Run npm run generate:hooks.");
  }
} else {
  fs.writeFileSync(output, installer, { mode: 0o755 });
}
