# Generated by scripts/generate-agent-contract.mjs. Do not edit.
import json as _json

AGENT_CONTRACT_VERSION = 1

AGENT_READY = "WMUX_AGENT_READY"
AGENT_RESULT = "WMUX_AGENT_RESULT"
AGENT_DONE = "WMUX_AGENT_DONE"
AGENT_TUI_READY = "WMUX_AGENT_TUI_READY"
AGENT_TUI_LAUNCH = "WMUX_AGENT_TUI_LAUNCH"
AGENT_TUI_ACK = "WMUX_AGENT_TUI_ACK"
AGENT_TUI_EXIT = "WMUX_AGENT_TUI_EXIT"
AGENT_TUI_RELEASE = "WMUX_AGENT_TUI_RELEASE"

MAX_LINE = 1100000
MAX_PROMPT = 131072
MAX_TEXT = 64000
TERMINATION_GRACE = 2
HELP_PROBE_TIMEOUT = 5
MAX_HELP_OUTPUT = 262144
MAX_BLANK_REQUEST_LINES = 8
MAX_RUN_ID = 128
MAX_DIRECTORY = 4096
MAX_OPTION_TEXT = 512

RUNTIMES = frozenset(("opencode", "codex", "claude"))
SANDBOX_MODES = frozenset(("read-only", "workspace-write", "danger-full-access"))
RESULT_FORMATS = frozenset(("outcome-v1",))
OUTCOME_SCHEMA = _json.loads("{\"type\":\"object\",\"properties\":{\"outcome\":{\"type\":\"string\",\"enum\":[\"completed\",\"blocked\",\"failed\"]},\"summary\":{\"type\":\"string\"}},\"required\":[\"outcome\",\"summary\"],\"additionalProperties\":false}")
